### ISSUE TITLE
Problem with gulp-watch

### ISSUE THREAD

**Issue by trendfischer** [nknapp/bootprint#8]
I am really glad, I found this lib to build static HTML for my swagger.json. Now, I'd like to automatically build an api documentation using gulp. The following configuration works so far:

```js
var gulp = require('gulp');

gulp.task('default', [
    'bootprint-swagger',
    'watch'
], function () {
});

gulp.task('bootprint-swagger', [], function () {
    require('bootprint')
      .load(require('bootprint-swagger'))
      .build('public/doc/swagger.json', 'public/doc/')
      .generate()
      .done(console.log);
});

gulp.task('watch', function() {
  gulp.watch([
      'public/doc/swagger.json'
  ], ['bootprint-swagger']);
});
```

On start of the default task, everything is built fine:

```
[13:35:33] Starting 'bootprint-swagger'...
Loading bootprint-swagger 0.13.1
Loading bootprint-json-schema 0.8.4
Loading bootprint-base 0.6.3
[13:35:33] Finished 'bootprint-swagger' after 66 ms
[13:35:33] Starting 'watch'...
[13:35:33] Finished 'watch' after 8.35 ms
```

 As soon as I change the swagger.json, I get the following logs:

```
[13:35:51] Starting 'bootprint-swagger'...
Loading bootprint-swagger 0.13.1
Loading bootprint-json-schema 0.8.4
Loading bootprint-base 0.6.3
[13:35:51] Finished 'bootprint-swagger' after 19 ms
[ 'public/doc/index.html',
  'public/doc/main.css',
  'public/doc/main.css.map' ]
```

So far, it seems ok. But there are no changes in the HTML-Output, just the timestamp is new. It seems, it uses the old unchanged swagger.json. Is there perhaps a global cache for the used json file or something like this?

**Comment by nknapp** [comment]
I had to think about it myself, but now that you mention it: Yes, there is a cache. It's [in line 75 of the index.js-file](https://github.com/nknapp/bootprint/blob/master/index.js#L75). I thought it would be useful if you could not only specify JSON-files as input, but JavaScript-Files as well. At least, you can use comments in JavaScript, which you can't do very well in JSON.
So, the loading of the input file is handled using `require()`, which of course means that they are cached.
Sorry for the inconvenience...

I'll see if this can be fixed by deleting the cached data from the [require.cache](https://nodejs.org/docs/latest/api/globals.html#globals_require_cache)-object.

**Comment by nknapp** [comment]
@trendfischer: I have made this change in the master-branch without testing. Would you mind trying that version (`npm install --save nknapp/bootprint`) in your gulp setup?

In my eyes, it is just a hotfix. I'm also working on the real solution (which has to be done for handlebars-helpers and the preprocessor as well, and will be part of the `customize-engine-handlebars`-module so that is also works when calling bootprint with the `-d` parameter to activate the built-in file-watcher.

But for now, if this fix works, I'll publish it.

**Comment by trendfischer** [comment]
@nknapp Great, I've tested the patch and it works like a charm. Thanks.
